import type { Request } from "express";
import type { Session } from "express-session";
export declare const testView = "*testView";
export declare const testUpdate = "*testUpdate";
export declare const testAdmin = "*testAdmin";
export declare const portNumber = 7000;
export declare const fakeViewOnlySession: Session;
export declare const fakeAdminSession: Session;
export declare const fakeRequest: Request;
export declare const fakeViewOnlyRequest: any;
export declare const fakeAdminRequest: any;
