import { Router } from 'express';
import handler_edit from '../handlers/licences-get/edit.js';
import handler_licenceCategorySummary from '../handlers/licences-get/licenceCategorySummary.js';
import handler_new from '../handlers/licences-get/new.js';
import handler_print from '../handlers/licences-get/print.js';
import handler_search from '../handlers/licences-get/search.js';
import handler_view from '../handlers/licences-get/view.js';
import handler_doAddAdditionalFee from '../handlers/licences-post/doAddAdditionalFee.js';
import handler_doAddLicenceTransaction from '../handlers/licences-post/doAddLicenceTransaction.js';
import handler_doAddRelatedLicence from '../handlers/licences-post/doAddRelatedLicence.js';
import handler_doCreateLicence from '../handlers/licences-post/doCreateLicence.js';
import handler_doDeleteAdditionalFee from '../handlers/licences-post/doDeleteAdditionalFee.js';
import handler_doDeleteLicence from '../handlers/licences-post/doDeleteLicence.js';
import handler_doDeleteLicenceTransaction from '../handlers/licences-post/doDeleteLicenceTransaction.js';
import handler_doDeleteRelatedLicence from '../handlers/licences-post/doDeleteRelatedLicence.js';
import handler_doGetBankName from '../handlers/licences-post/doGetBankName.js';
import handler_doGetLicenceCategory from '../handlers/licences-post/doGetLicenceCategory.js';
import handler_doGetLicenceCategorySummary from '../handlers/licences-post/doGetLicenceCategorySummary.js';
import handler_doGetLicenceEndDate from '../handlers/licences-post/doGetLicenceEndDate.js';
import handler_doGetRelatableLicences from '../handlers/licences-post/doGetRelatableLicences.js';
import handler_doIssueLicence from '../handlers/licences-post/doIssueLicence.js';
import handler_doSearch from '../handlers/licences-post/doSearch.js';
import handler_doUpdateLicence from '../handlers/licences-post/doUpdateLicence.js';
import * as permissionHandlers from '../handlers/permissions.js';
export const router = Router();
router.get('/', handler_search);
router.post('/doSearch', handler_doSearch);
router.get('/licenceCategorySummary', handler_licenceCategorySummary);
router.post('/doGetLicenceCategorySummary', handler_doGetLicenceCategorySummary);
router.get('/new', permissionHandlers.updateGetHandler, handler_new);
router.get('/:licenceId', handler_view);
router.get('/:licenceId/edit', permissionHandlers.updateGetHandler, handler_edit);
router.post('/doGetLicenceCategory', permissionHandlers.updatePostHandler, handler_doGetLicenceCategory);
router.post('/doGetLicenceEndDate', permissionHandlers.updatePostHandler, handler_doGetLicenceEndDate);
router.post('/doCreateLicence', permissionHandlers.updatePostHandler, handler_doCreateLicence);
router.post('/doUpdateLicence', permissionHandlers.updatePostHandler, handler_doUpdateLicence);
router.post('/doIssueLicence', permissionHandlers.updatePostHandler, handler_doIssueLicence);
router.post('/doDeleteLicence', permissionHandlers.updatePostHandler, handler_doDeleteLicence);
router.post('/doGetRelatableLicences', permissionHandlers.updatePostHandler, handler_doGetRelatableLicences);
router.post('/doAddRelatedLicence', permissionHandlers.updatePostHandler, handler_doAddRelatedLicence);
router.post('/doDeleteRelatedLicence', permissionHandlers.updatePostHandler, handler_doDeleteRelatedLicence);
router.post('/doGetBankName', permissionHandlers.updatePostHandler, handler_doGetBankName);
router.post('/doAddAdditionalFee', permissionHandlers.updatePostHandler, handler_doAddAdditionalFee);
router.post('/doDeleteAdditionalFee', permissionHandlers.updatePostHandler, handler_doDeleteAdditionalFee);
router.post('/doAddLicenceTransaction', permissionHandlers.updatePostHandler, handler_doAddLicenceTransaction);
router.post('/doDeleteLicenceTransaction', permissionHandlers.updatePostHandler, handler_doDeleteLicenceTransaction);
router.get('/:licenceId/print', handler_print);
export default router;
